apiVersion: v1alpha
kind: xcuitest
sauce:
  region: us-west-1
  concurrency: 1
  metadata:
    tags:
      - e2e
      - release team
      - other tag
    build: Release $CI_COMMIT_SHORT_SHA

xcuitest:
  app: ./apps/SauceLabs-Demo-App.ipa
  testApp: ./apps/SauceLabs-Demo-App-Runner.XCUITest.ipa

suites:
  - name: "saucy xcuitest"
    testOptions:
      notClass: ["My_Demo_AppUITests.NavigationTest"]
    devices:
      # If set, only device by ID will be queried.
      #- id: <rdc_device_id>
      - name: "iPhone.*"
        options:
          # If set, only devices with a SIM card will be queried.
          carrierConnectivity: false
          # Possible values [ANY,PHONE,TABLET]
          deviceType: ANY
          # If set, only private devices will be queried.
          private: false

artifacts:
  download:
    when: always
    match:
      - "*.junit.xml"
    directory: ./artifacts/
